### ISSUE TITLE
SQLSTATE[HY000]: General error: 1005

### ISSUE THREAD

**Issue by atmacoder** [Silvanite/brandenburg#19]
SQLSTATE[HY000]: General error: 1005 Can't create table 'mydatabasew.#sql-40a1_67' (errno: 150) (SQL: alter table `role_user` add constraint `role_user_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)

How to fix this?
laravel 6
php 7.3

**Comment by alisholihindev** [comment]
hey.. you need create user table first..
its error because you dont have user table..

**Comment by atmacoder** [comment]
> hey.. you need create user table first..
> its error because you dont have user table..

first 
Migrating: 2014_10_12_000000_create_users_table
then this error on
Migrating: 2017_05_28_115649_create_gates_table

same stuff working on localhost, but on dedicated not working...

**Comment by atmacoder** [comment]
ok it fixed, i change users id from Increments to bigIncrements, and now it works...
 Schema::create('users', function (Blueprint $table) {
            $table->bigIncrements('id');
}
