### ISSUE TITLE
Support for Laravel 7

### ISSUE THREAD

**Issue by packytagliaferro** [Silvanite/brandenburg#20]
Will you be adding 7 support? Current version wont install.

**Comment by m2de** [comment]
Yes, it should work but haven't had any need to upgrade any of my projects to 7 yet. Will try and push an update asap unless someone wants to open a PR in the meantime.

Apologies for the slow response.

Cheers.

**Comment by ChandlerVS** [comment]
I have opened pull request #21 which should take care of this.

**Comment by m2de** [comment]
Resolved by #21 . Thanks @ChandlerVS .
